add support for georss
GeoXForm/GeoXForm pull request #7
Opened 2016-10-04 20:14 UTC by jgravois

resolves #6

2016-10-04 20:21 UTC, dmfenton requested changes
This looks great! Would you be willing to post the results of a geojson to georss conversion so we can eyeball the results?

2016-10-04 20:21 UTC, dmfenton commented on src/lib/ogr-cmd.js
> +  console.log(cmd)
please remove

2016-10-04 21:27 UTC, jgravois commented
> Would you be willing to post the results of a geojson to georss conversion so we can eyeball the results?

of course!
```xml
<?xml version="1.0"?>
<rss version="2.0" xmlns:georss="http://www.georss.org/georss">
  <channel>
    <title>title</title>
    <description>channel_description</description>
    <link>channel_link</link>
    <item>
      <title>Feature 1</title>
      <ogr:FID>1</ogr:FID>
      <ogr:rownum>1</ogr:rownum>
      <ogr:latitude>40</ogr:latitude>
      <ogr:longitude>-88</ogr:longitude>
      <quant:val>1002</quant:val>
      <expected:c>red</expected:c>
      <FID:1>1</FID:1>
      <georss:point>40 -88</georss:point>
    </item>
    <item>
      <title>Feature 2</title>
      <ogr:FID>2</ogr:FID>
      <ogr:rownum>2</ogr:rownum>
      <ogr:latitude>40</ogr:latitude>
      <ogr:longitude>-87.9</ogr:longitude>
      <quant:val>1003</quant:val>
      <expected:c>red</expected:c>
      <FID:1>2</FID:1>
      <georss:point>40.0 -87.9</georss:point>
    </item>
    <!-- many more -->
  </channel>
</rss>
```

2016-10-04 21:28 UTC, jgravois commented on src/lib/ogr-cmd.js
> +  console.log(cmd)
whoops.  thought i caught that.

2016-10-04 22:09 UTC, jgravois commented
should we populate the title, description and link fields?
```xml
<title>koop</title>
<description>Transform, query, and download geospatial data on the web</description>
<link>http://koopjs.github.io/</link>
```
maybe even dig something relevant out of the input?

2016-10-04 23:23 UTC, dmfenton commented
Good idea to support that if the options are passed in, but shouldn't be required

2016-10-05 18:38 UTC, ajturner commented
@juliekdang - you may want to see this PR since you just asked yesterday.

2016-10-05 18:39 UTC, dmfenton approved these changes

2016-10-05 18:40 UTC, merged

2016-10-05 18:40 UTC, dmfenton commented
@jgravois I'm going to merge this as is. Title, description and link can come next.

2016-10-05 18:53 UTC, jgravois commented
sounds good to me!